### ISSUE TITLE
get_packet_id.py有关问题

### ISSUE THREAD

**Issue by 2054686334** [c2c3vsfac/Iridium-utils#1]
使用将https://github.com/NickTheHuy/3.6_protos/tree/main/obfuscated中的文件放入proto文件夹后运行get_packet_id.py，不会报错，正常生成文件，但是文件是一个空的json串{}。

**Comment by c2c3vsfac** [comment]
这问题自己动手改一改就好了呀，他们输出的格式经常变，稍微适配一下就好了。还有，你用的文件夹错了，obfuscated是混淆的意思，你应该用deobfuscated，不然你看抓包数据就跟看天书一样。
