### ISSUE TITLE
Bug in proto2json.py

### ISSUE THREAD

**Issue by Guiltylife** [c2c3vsfac/Iridium-utils#2]
Hello, I want to report a bug in proto2json.py. When I try to conevert version 3.7 protos files, it raise some errors. The proto file that cause the error is this [GadgetPlayInfo.txt](https://github.com/c2c3vsfac/Iridium-utils/files/11815662/GadgetPlayInfo.txt) (You need to change the file type first). I think the reason for the bug is that the code can't deal with the "optional" key word in "message" in the proto file. Hope you can fix this bug soon. Thanks.

你好，我在使用你的程序proto2json.py处理3.7版本的protos文件时出现了报错，导致报错的proto文件已经在上面提到过了。我认为这个报错的原因是程序无法正确处理proto文件中message字段下的optional关键词。期待你可以尽快修复这个bug。谢谢。

**Comment by c2c3vsfac** [comment]
哈，这个我改过了，optional在proto3就是个多余的关键词，去掉它就好了，很简单的啦，你自己改下就好了。我等过几天3.8再说。

**Comment by Guiltylife** [comment]
好的，感谢你的回复。我已经解决相关问题
